replicaCount: 1

image:
  repository: ghcr.io/mhsanaei/3x-ui
  pullPolicy: IfNotPresent
  tag: v2.5.7

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 2053
  wsPort: 44932

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: admin.rubystay.vn
      paths:
        - path: /adm
          pathType: Prefix
          port: 2053
    - host: ws.rubystay.vn
      paths:
        - path: /
          pathType: Prefix
          port: 44932

  tls:
    - secretName: admin-rubystay-tls
      hosts:
        - admin.rubystay.vn
    - secretName: ws-rubystay-tls
      hosts:
        - ws.rubystay.vn

resources: {}

livenessProbe:
  httpGet:
    path: /adm/
    port: 2053

readinessProbe:
  httpGet:
    path: /adm/
    port: 2053

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: db
    persistentVolumeClaim:
      claimName: v2ray-db
  - name: cert
    persistentVolumeClaim:
      claimName: v2ray-cert

volumeMounts:
  - name: db
    mountPath: /etc/x-ui
  - name: cert
    mountPath: /root/cert

nodeSelector:
  node-role.kubernetes.io/master: "true"

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: "nfs-sc"  # здесь укажешь свой класс
  db:
    size: 1Gi
  cert:
    size: 1Gi
