apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2ray.fullname" . }}
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.wsPort | default 44932 }}
      targetPort: 44932
      protocol: TCP
      name: ws
    - port: {{ .Values.service.subPort | default 2096 }}
      targetPort: 2096
      protocol: TCP
      name: subport
  selector:
    {{- include "v2ray.selectorLabels" . | nindent 4 }}
